import { Deployment } from "./types";

export const mockDeployments: Deployment[] = [
  {
    id: "dep-1",
    name: "full-stack-app",
    status: "running",
    application: "Full Stack Web Application",
    user: {
      address: "0x1234...5678",
      name: "Alice",
    },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    pricePerHour: "2.5",
    leaseEndAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days from now
    autoRenew: true,
    commitment: "month",
    totalResources: {
      cpu: 6,
      memory: 12,
      storage: 80,
    },
    services: [
      {
        id: "svc-1-1",
        name: "web",
        image: "nginx:latest",
        status: "running",
        replicas: 3,
        replicasStatus: {
          running: 3,
          pending: 0,
          failed: 0,
          succeeded: 0,
          total: 3,
        },
        replicasList: [
          {
            id: "pod-1-1-1",
            name: "web-7d8f9b2c-abc12",
            status: "running",
            nodeId: "node-1",
            nodeName: "worker-01",
            startedAt: "2024-01-15T10:05:00Z",
            uptime: 99.8,
          },
          {
            id: "pod-1-1-2",
            name: "web-7d8f9b2c-def34",
            status: "running",
            nodeId: "node-2",
            nodeName: "worker-02",
            startedAt: "2024-01-15T10:05:15Z",
            uptime: 99.5,
          },
          {
            id: "pod-1-1-3",
            name: "web-7d8f9b2c-ghi56",
            status: "running",
            nodeId: "node-1",
            nodeName: "worker-01",
            startedAt: "2024-01-15T10:05:30Z",
            uptime: 99.2,
          },
        ],
        ports: [
          {
            containerPort: 80,
            hostPort: 8080,
            protocol: "tcp",
            url: "https://full-stack-app.subnet.example.com",
          },
          { containerPort: 443, hostPort: 8443, protocol: "tcp" },
        ],
        resources: {
          cpu: 2,
          memory: 4,
          storage: 20,
        },
        uptime: 99.5,
      },
      {
        id: "svc-1-2",
        name: "api",
        image: "node:20-alpine",
        status: "running",
        replicas: 2,
        replicasStatus: {
          running: 2,
          pending: 0,
          failed: 0,
          succeeded: 0,
          total: 2,
        },
        replicasList: [
          {
            id: "pod-1-2-1",
            name: "api-5a3b4c5d-xyz78",
            status: "running",
            nodeId: "node-2",
            nodeName: "worker-02",
            startedAt: "2024-01-15T10:10:00Z",
            uptime: 98.5,
          },
          {
            id: "pod-1-2-2",
            name: "api-5a3b4c5d-uvw90",
            status: "running",
            nodeId: "node-3",
            nodeName: "worker-03",
            startedAt: "2024-01-15T10:10:20Z",
            uptime: 97.9,
          },
        ],
        ports: [{ containerPort: 3000, hostPort: 3001, protocol: "tcp" }],
        resources: {
          cpu: 2,
          memory: 4,
          storage: 30,
        },
        uptime: 98.2,
      },
      {
        id: "svc-1-3",
        name: "database",
        image: "postgres:15-alpine",
        status: "running",
        replicas: 1,
        replicasStatus: {
          running: 1,
          pending: 0,
          failed: 0,
          succeeded: 0,
          total: 1,
        },
        replicasList: [
          {
            id: "pod-1-3-1",
            name: "database-3f4g5h6i-pqr12",
            status: "running",
            nodeId: "node-1",
            nodeName: "worker-01",
            startedAt: "2024-01-15T10:15:00Z",
            uptime: 99.8,
          },
        ],
        ports: [{ containerPort: 5432, hostPort: 5432, protocol: "tcp" }],
        resources: {
          cpu: 2,
          memory: 4,
          storage: 30,
        },
        uptime: 99.8,
      },
    ],
  },
  {
    id: "dep-2",
    name: "microservices-api",
    status: "running",
    application: "Microservices API Gateway",
    user: {
      address: "0xabcd...ef01",
    },
    createdAt: "2024-01-18T08:00:00Z",
    updatedAt: "2024-01-20T15:00:00Z",
    pricePerHour: "1.8",
    leaseEndAt: new Date(Date.now() + 1000 * 60 * 60 * 12).toISOString(), // 12 hours from now
    autoRenew: false,
    commitment: "day",
    totalResources: {
      cpu: 4,
      memory: 8,
      storage: 40,
    },
    services: [
      {
        id: "svc-2-1",
        name: "gateway",
        image: "kong:latest",
        status: "running",
        replicas: 2,
        replicasStatus: {
          running: 2,
          pending: 0,
          failed: 0,
          succeeded: 0,
          total: 2,
        },
        replicasList: [
          {
            id: "pod-2-1-1",
            name: "gateway-8b9c0d1e-abc34",
            status: "running",
            nodeId: "node-2",
            nodeName: "worker-02",
            startedAt: "2024-01-18T08:05:00Z",
            uptime: 97.8,
          },
          {
            id: "pod-2-1-2",
            name: "gateway-8b9c0d1e-def56",
            status: "running",
            nodeId: "node-3",
            nodeName: "worker-03",
            startedAt: "2024-01-18T08:05:20Z",
            uptime: 97.2,
          },
        ],
        ports: [
          {
            containerPort: 8000,
            hostPort: 8000,
            protocol: "tcp",
            url: "https://gateway.subnet.example.com",
          },
          { containerPort: 8443, hostPort: 8443, protocol: "tcp" },
        ],
        resources: {
          cpu: 2,
          memory: 4,
          storage: 20,
        },
        uptime: 97.5,
      },
      {
        id: "svc-2-2",
        name: "auth-service",
        image: "auth-service:v1.2",
        status: "running",
        replicas: 3,
        replicasStatus: {
          running: 3,
          pending: 0,
          failed: 0,
          succeeded: 0,
          total: 3,
        },
        replicasList: [
          {
            id: "pod-2-2-1",
            name: "auth-service-9c0d1e2f-ghi78",
            status: "running",
            nodeId: "node-1",
            nodeName: "worker-01",
            startedAt: "2024-01-18T08:10:00Z",
            uptime: 98.3,
          },
          {
            id: "pod-2-2-2",
            name: "auth-service-9c0d1e2f-jkl90",
            status: "running",
            nodeId: "node-2",
            nodeName: "worker-02",
            startedAt: "2024-01-18T08:10:15Z",
            uptime: 97.8,
          },
          {
            id: "pod-2-2-3",
            name: "auth-service-9c0d1e2f-mno12",
            status: "running",
            nodeId: "node-3",
            nodeName: "worker-03",
            startedAt: "2024-01-18T08:10:30Z",
            uptime: 97.9,
          },
        ],
        ports: [{ containerPort: 3000, hostPort: 3002, protocol: "tcp" }],
        resources: {
          cpu: 1,
          memory: 2,
          storage: 10,
        },
        uptime: 98.0,
      },
      {
        id: "svc-2-3",
        name: "cache",
        image: "redis:7-alpine",
        status: "stopped",
        replicas: 1,
        replicasStatus: {
          running: 0,
          pending: 0,
          failed: 0,
          succeeded: 0,
          total: 0,
        },
        replicasList: [],
        ports: [{ containerPort: 6379, hostPort: 6379, protocol: "tcp" }],
        resources: {
          cpu: 1,
          memory: 2,
          storage: 10,
        },
        uptime: 0,
      },
    ],
  },
  {
    id: "dep-3",
    name: "analytics-platform",
    status: "stopped",
    application: "Data Analytics Platform",
    user: {
      address: "0x5678...9012",
      name: "Bob",
    },
    createdAt: "2024-01-10T12:00:00Z",
    updatedAt: "2024-01-19T10:00:00Z",
    pricePerHour: "3.2",
    leaseEndAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // expired 1 day ago
    autoRenew: false,
    commitment: "week",
    totalResources: {
      cpu: 8,
      memory: 16,
      storage: 100,
    },
    services: [
      {
        id: "svc-3-1",
        name: "spark-master",
        image: "bitnami/spark:latest",
        status: "stopped",
        replicas: 1,
        replicasStatus: {
          running: 0,
          pending: 0,
          failed: 0,
          succeeded: 0,
          total: 0,
        },
        replicasList: [],
        ports: [{ containerPort: 8080, hostPort: 8081, protocol: "tcp" }],
        resources: {
          cpu: 4,
          memory: 8,
          storage: 50,
        },
        uptime: 0,
      },
      {
        id: "svc-3-2",
        name: "spark-worker",
        image: "bitnami/spark:latest",
        status: "stopped",
        replicas: 3,
        replicasStatus: {
          running: 0,
          pending: 0,
          failed: 0,
          succeeded: 0,
          total: 0,
        },
        replicasList: [],
        ports: [],
        resources: {
          cpu: 4,
          memory: 8,
          storage: 50,
        },
        uptime: 0,
      },
    ],
  },
];

